### ISSUE TITLE
Crypto not defined

### ISSUE THREAD

**Issue by gadgetalex** [BlaT2512/homebridge-spanet#10]
**Describe The Bug:**
Issue with password - causes home bridge to shut down. 

**To Reproduce:**
Install app and login with Spanet account

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
[04/11/2023, 16:49:47] ReferenceError: crypto is not defined
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-spanet/src/platform.ts:25:27)
    at HomebridgeAPI.emit (node:events:525:35)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:190:14)
[04/11/2023, 16:49:47] Got SIGTERM, shutting down Homebridge...
[04/11/2023, 16:49:47] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:513:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge DF54",
        "username": "0E:BD:1D:F7:DF:54",
        "port": 51062,
        "pin": "190-99-900",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "REMOVED"
            },
            "platform": "Nest"
        },
        {
            "email": "thegadgetguy@hotmail.co.uk",
            "password": "REMOVED",
            "spaName": "Hot Tub",
            "platform": "SpaNETPlugin"
        }
    ],
    "disabledPlugins": [
        "@o-lukas/homebridge-smartthings-tv"
    ]
}```

**Environment:**

* **Plugin Version**: v2.0.0
* **Homebridge Version**: V1.7.0
* **Node.js Version**: v18.16.0
* **NPM Version**: <!-- npm -v -->
* **Operating System**: <!-- Raspbian  -->

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by BlaT2512** [comment]
Thanks - will fix this small bug with 2.0.1 update in next couple hours
